### ISSUE TITLE
Implementation of your algorithm

### ISSUE THREAD

**Issue by moredatapls** [tracyhenry/xClean#1]
Hi, I discovered your paper and I would like to use your algorithm in my own research. I've been trying to wrap my head around your implementation and I was wondering two things:

1. within `RuleGenerator/`, which one is your implementation of the rule generation that you used in the comparison in your paper? I assume it's one of the *LCS ones, but which one exactly?
2. within `Joiner/`, which one is your implementation of the join algorithm?

Thanks!

**Comment by tracyhenry** [comment]
As I can recall, it's either Badboy or MyRule for rule generation, and PolynomialJoiner for join algorithm

You should double check though, it's been a long time for me.
